# Generated by Django 4.2.30 on 2026-06-14 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, default='', max_length=10)),
                ('flag_url', models.URLField(blank=True, default='')),
                ('country_code', models.CharField(blank=True, default='', max_length=2)),
                ('group_name', models.CharField(blank=True, max_length=10, null=True)),
                ('points', models.IntegerField(default=0)),
                ('played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('goal_diff', models.IntegerField(default=0)),
                ('group_position', models.IntegerField(blank=True, null=True)),
                ('tournament_stage', models.CharField(default='group', max_length=50)),
            ],
            options={
                'ordering': ['group_name', 'group_position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_fixture_id', models.IntegerField(unique=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='scheduled', max_length=50)),
                ('date', models.DateTimeField()),
                ('stage', models.CharField(blank=True, default='', max_length=100)),
                ('round', models.CharField(blank=True, default='', max_length=100)),
                ('venue', models.CharField(blank=True, default='', max_length=200)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='league.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='league.team')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PersonTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_teams', to='league.person')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_persons', to='league.team')),
            ],
            options={
                'unique_together': {('person', 'team')},
            },
        ),
    ]
