# Generated by Django 4.2.30 on 2026-06-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
